const mobileData=[
    {
    "Model_name":"Google Pixel",
    "company":"Google",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"10 january 2021",
    "frontCamera":"10000MP",
    "backCamera":"50MP",
    "battery":"4800mAh",
    
    },
    {
        "Model_name":"iPhone 14 Pro max",
        "company":"Apple",
        "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
        "launch by date":"7 september 2022",
        "front camera":"12MP",
        "back camera":"48MP",
        "battery":"4323mAh",
    
    },
      {
        "Model_name":"Realme 8",
        "company":"Realme",
        "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
        "launch by date":"24 March 2021",
        "front camera":"16MP",
        "back camera":"64MP",
        "battery":"5000mAh",
    
    }, 
    {
      "Model_name":"Realme 7",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"15 sept 2020",
    "front camera":"16MP",
    "back camera":"64MP",
    "battery":"5000mAh",
    
    },
    {
      "Model_name":"Poco X3",
    "company":"Xiaomi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"22 march 2021",
    "front camera":"20MP",
    "back camera":"66MP",
    "battery":"5160mAh",
    
    },
     {
      "Model_name":"Redmi %A",
    "company":"Xiaomi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"22 march 2018",
    "front camera":"16MP",
    "back camera":"8MP",
    "battery":"2700mAh",
    
    },
    {
      "Model_name":"Poco X4 PRO 5G",
    "company":"Xiaomi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"28 feburary 2022",
    "front camera":"16MP",
    "back camera":"108MP",
    "battery":"5000mAh",
    
    },
   
    {
      "Model_name":"Redmi 9A",
    "company":"Xiaomi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"30th June 2020",
    "front camera":"5MP",
    "back camera":"13MP",
    "battery":"5000mAh",
    
    },
    
  {
    "Model_name":"Samsung Galaxy S22 Ultra 5G",
        "company":"Samsung",
        "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    
        "battery":"4323mAh",
    
    },
    {
      "Model_name":"Redmi Note 11",
    "company":"Redmi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
  
    "battery":"4323mAh",
    
  
    },
  {
    "Model_name":"Samsung",
    "company":"Galaxy M53 5G",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
  
    "battery":"5000mAh",
    
    },
   {
    "Model_name":"Realme 9 Pro 5G",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"28 feburary 2022",
    "front camera":"16MP",
    "back camera":"64MP",
    "battery":"5000mAh",
    
    },
    {
    "Model_name":"Iphone 12",
    "company":"Apple",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"28 October 2020",
    "front camera":"8MP",
    "back camera":"12MP",
    "battery":"3100mAh",
   
    },
    
    {
    "Model_name":"Samsung Galaxy S20 FE",
    "company":"Samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"31st March 2021",
    "front camera":"32MP",
    "back camera":"12MP + 8MP + 12MP",
    "battery":"4500mAh",
  
    },
   
    {
    "Model_name":"Apple 14 PRO",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"3 September 2020",
    "front camera":"32MP",
    "back camera":"64MP",
    "battery":"4500mAh",
    
    },
  
    {
    "Model_name":"Oppo Reno 6 5G",
    "company":"Oppo",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"14 July 2021",
    "front camera":"32MP",
    "back camera":"64MP",
    "battery":"4300mAh",
    
    },
    {
    "Model_name":"One Plus Nord 2",
    "company":"One Plus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"28 July 2021",
    "front camera":"32MP",
    "back camera":"50MP",
    "battery":"4500mAh",
    
    },
     {
    "Model_name":"S22ultra",
    "company":"Samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"25 February 2022",
    "front camera":"32MP",
    "back camera":"64MP",
    "battery":"5500mAh",
    
    },
    {
    "Model_name":"OnePlus Nord 2T 5G ",
    "company":"Oneplus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"July 01, 2022",
    "front camera":"32MP",
    "back camera":"50MP",
    "battery":"4500mAh",
    
    },
    {
    "Model_name":"Redmi Note 9 Pro Max",
    "company":"Xiaomi Redmi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"March 2020",
    "front camera":"32MP",
    "back camera":"64MP",
    "battery":"5020mAh",
    
    },
    {
    "Model_name":"Redmi Y3",
    "company":"Redmi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"April 2019",
    "front camera":"32MP",
    "back camera":"dual 12-megapixel and 2-megapixel",
    "battery":"4000mAh",
    
    },
    {
    "Model_name":"Samsung a20",
    "company":"samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"3 September 2020",
    "front camera":"32MP",
    "back camera":"12MP",
    "battery":"4500mAh",
    
    },
    {
    "Model_name":"Samsung f41",
    "company":"samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"8 October 2020",
    "front camera":"32MP",
    "back camera":"64MP",
    "battery":"6000mAh",
    
    },
  
    {
    "Model_name":"Realme 6i",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date": "July 31, 2020",
    "front camera":"16MP",
    "back camera":"48MP",
    "battery":"5000mAh",
    
    },
        
    {
    "Model_name":"Oneplus 10 Pro",
    "company":"Oneplus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"31 March 2022",
    "front camera":"32Mp",
    "back camera":"50MP",
    "battery":"4500mAh",
    
    },
     {
    "Model_name":"OnePlus Ace Pro",
    "company":"OnePlus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"9 august 2022",
    "front camera":"16MP",
    "back camera":"50MP",
    "battery":"4800mAh",
    
    },
    {
    "Model_name":"iPhone 13",
    "company":"Apple",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"14 September 2021",
    "front camera":"12MP",
    "back camera":"12MP + 12MP",
    "battery":"3227mAh",
    
    },    
    {
    "Model_name":"Redmi Note 10 5G",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"4 March 2021",
    "front camera":"8MP",
    "back camera":"48MP",
    "battery":"5000mAh"
    },
    {
    "Model_name":"Reaalme 9 pro plus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"16 february 2022",
    "front camera":"16 MP",
    "back camera":"50 MP + 8 MP + 2 MP",
    "battery":"4500 mAh",
    },
     {
    "Model_name":"vivo v23",
    "company":"vivo",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":  "5 th january 2022",
    "front camera":"50 MP",
    "back camera":"108 MP + 8 MP + 2 MP",
    "battery":"4200 mAh",
    
    },
    { 
  
    "Model_name":"Reaalme 9 pro plus",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"16 february 2022",
    "front camera":"16 MP",
    "back camera":"50 MP + 8 MP + 2 MP",
    "battery":"4500 mAh",
  
    },
  
    {
    "Model_name":"poco m2 pro",
    "company":"MI",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"4 March 2019",
    "front camera":"16MP",
    "back camera":"48MP",
    "battery":"5000mAh",
    
    },
  
    {
    "Model_name":"Realme 8s 5g",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"13 September 2021",
    "front camera":"16MP",
    "back camera":"64MP + 2MP +2MP",
    "battery":"5000mAh",
   
    },
  {
    "Model_name":"Vivo V21 5g",
    "company":"Vivo",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"27 April 2021",
    "front camera":"32MP",
    "back camera":"64MP + 8MP",
    "battery":"4000mAh",
    
  
    },
  
    {
    "Model_name":"VIVO V21E 5G",
    "company":"VIVO",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"27 April 2021",
    "front camera":"32MP",
    "back camera":"64MP + 8MP",
    "battery":"4000mAh",
    
    },
  
  {
    "Model_name":"realme 8s 5G",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"133 September 2021",
    "front camera":"16MP",
    "back camera":"64MP + 8MP",
    "battery":"6000mAh",
    
    },
    {
    "Model_name":"OnePlus 10T 5G",
    "company":"OnePlus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"03 August 2022",
    "front camera":"16MP",
    "back camera":"50MP + 08MP + 02MP",
    "battery":"4800mAh",
    
    },
   {
    "Model_name":"Lenovo Legion Y70",
    "company":"Lenovo",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"18 Augudt 2022",
    "front camera":"16MP",
    "back camera":"50MP + 13MP",
    "battery":"5100mAh",
    
  
  },
  {
    "Model_name":"Redmi Note 11",
    "company":"Redmi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"26 January 2022",
    "front camera":"13MP",
    "back camera":"50MP + 8MP + 2MP + 2MP",
    "battery":"5000mAh",
    
    },
    {
    "Model_name":"OnePlus Nord cE",
    "company":"OnePlus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"10th June 2021",
    "front camera":"16MP",
    "back camera":"64MP+8MP+2MP",
    "battery":"5000mAh",
    
  
    },
  
    {
    "Model_name":"Samsung Galaxy S8",
    "company":"Samasung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"21 April 2017",
    "front camera":"8MP",
    "back camera":"12MP",
    "battery":"3000 mAh",
    },
    {
    "Model_name":"Samsung A23",
    "company":"Samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"5th March 2022",
    "front camera":"8MP",
    "back camera":"50MP + 05MP + 02MP",
    "battery":"5000mAh",
    },
    {
    "Model_name":"Nokia 1100 ",
    "company":"Nokia",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"2003",
    "front camera":"Nil",
    "back camera":"Nil",
    "battery":"850 mAhh",
    },
    {
        "Model_name":"Motorola G71",
        "company":"Motorola",
        "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
        "launch by date":"29 october 2021",
        "front camera":"32MP",
        "back camera":"48MP + 8MP",
        "battery":"6000mAh",
    },
    
        {
        "Model_name":"Samsung A50",
        "company":"Samsung",
        "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
        "launch by date":"15 April 2019",
        "front camera":"25MP",
        "back camera":"25MP + 5MP + 8mp",
        "battery":"4000mAh",
    },
  {
        "Model_name":"Redmi Note 4",
        "company":"xiaomi",
        "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
        "launch by date":"August 2016",
        "front camera":"5MP",
        "back camera":"13MP",
        "battery":"4100mAh",
    },
  {
    "Model_name":"Realme 5 pro",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"april 2019",
    "front camera":"16MP",
    "back camera":"48MP + 8MP + 2MP + 2MP",
    "battery":"4035mAh",
    },
  {
    "Model_name":"Samsung A20",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"april 2028",
    "front camera":"14MP",
    "back camera":"48MP + 8MP + 2MP + 2MP",
    "battery":"4035mAh",
    },
  {
    "Model_name":"Redmi Note 7 Pro",
    "company":"Redmi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"april 2019",
    "front camera":"13MP",
    "back camera":"48MP + 5MP",
    "battery":"4000 mAh",
    }
  ,
  {
    "Model_name":"Samsung A21",
    "company":"Samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"april 2028",
    "front camera":"14MP",
    "back camera":"48MP + 8MP + 2MP + 2MP",
    "battery":"4035mAh",
    },
  {
    "Model_name":"POCO M4 5G",
    "company":"POCO",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"april 2028",
    "front camera":"8MP",
    "back camera":"20MP + 2MP ",
    "battery":"5000 mAh",
  },
  {
    "Model_name":"S20 FE 5g",
    "company":"SAMSUNG",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"May 2021",
    "front camera":"32MP",
    "back camera":"12MP + 12MP + 12MP",
    "battery":"4400 mAh",
  },
    {
    "Model_name":"Samsung Galaxy S20 FE 5G",
    "company":"Samsung",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"31st March 2021",
    "front camera":"32MP",
    "back camera":"12MP,8MP,12MP",
    "battery":"4500 mAh",
    
    },
  
    {
    "Model_name":"OnePlus 10T 5G",
    "company":"OnePlus",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"3 August 2022",
    "front camera":"16MP",
    "back camera":"50MP",
    "battery":"4800mAh",
    
    },
  
  {
    "Model_name":"Samsung S20 FE 5G",
    "company":"SAMSUNG",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"31st March 2021",
    "front camera":"32MP",
    "back camera":"12MP + 8MP + 12MP ",
    "battery":"4500 mAh",
  },
  
  {
    "Model_name":"Tecno Spark Power 2 Air",
    "company":"Tecno",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"14th September 2020",
    "front camera":"8MP",
    "back camera":"13MP",
    "battery":"6000 mAh",
  },
  
     {
    "Model_name":"Redmi Note 11 Pro 5G",
    "company":"Xiaomi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"26 january 2022",
    "front camera":"16MP",
    "back camera":"108MP",
    "battery":"5020 mAh",
    },
  
    {
    "Model_name":"iQOO Z6 Lite 5G",
    "company":"iQOO",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"14 September 2022",
    "front camera":"8MP",
    "back camera":"50MP+2MP",
    "battery":"5000 mAh",
    }
  ,
  {
    "Model_name":"Realme 9",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"10th March 2022",
    "front camera":"16MP",
    "back camera":"48MP + 2MP + 2MP",
    "battery":"5000 mAh",
 
  },
    {
    "Model_name":"Realme 9 pro",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"10th March 2022",
    "front camera":"16MP",
    "back camera":"48MP + 2MP + 2MP",
    "battery":"5000 mAh",
  
  },
    {
    "Model_name":"Realme 9 pro max",
    "company":"Realme",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"10th March 2022",
    "front camera":"16MP",
    "back camera":"48MP + 2MP + 2MP",
    "battery":"5000 mAh",

  },
     {
    "Model_name":"Oppo F17 pro",
    "company":"oppo",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"September 7, 2020",
    "front camera":"16MP",
    "back camera":"48MP+ 8 + 2MP + 2MP",
    "battery":"4015 mAh",
   
     },
  
     {
    "Model_name":"POCO F4 5G",
    "company":"Xiaomi",
    "price": "50000",
    " processor": "Tensor G2 Processor",
    "os":"Android 13",
    "imageUrl":"https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70" ,
    "launch by date":"23rd June 2021",
    "front camera":"20MP",
    "back camera":"64MP",
    "battery":"4500mAh",
    
     }
  
  ]
  module.exports=mobileData;